### ISSUE TITLE
Data export from Milvus 2.x standalone

### ISSUE THREAD

**Issue by jmrf** [milvus-io/milvus-tools#37]
Hi, 

I've tried to export Milvus data to `HDF5` when running Milvus in a standalone setup using dockerized `milvus`, `etcd` and `minio`.

The yaml configuration looks like:

```yaml
M2H:
  milvus_version: 2.0.0
  source_milvus_path: '<directory-where-milvus-volume-is-mapped>'
  mysql_parameter:
  source_collection:
    <my-collection-name>:
      - '_default'

  data_dir: '<data-directory-where-to-export>'
```

However this fails with:
`ERROR ｜ read_milvus_meta.py ｜ connect_sqlite ｜ 31 ｜ SQLite ERROR: connect failed with unable to open database file`

So I wonder if it is possible to use the tool from the standalone run Milvus?

Thanks!
